name: Test and publish service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-and-lint:
    uses: yeencloud/dpl-ci/.github/workflows/test-and-lint.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  bump-version:
    needs: test-and-lint
    uses: yeencloud/dpl-ci/.github/workflows/bump-version.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # we don't want this job to trigger a new pipeline run

  assign-issue-from-todo:
    needs: test-and-lint
    uses: yeencloud/dpl-ci/.github/workflows/issue-from-todo.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-and-publish:
    needs: bump-version
    uses: yeencloud/dpl-ci/.github/workflows/create-package.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  create-release:
    needs: build-and-publish
    uses: yeencloud/dpl-ci/.github/workflows/create-release.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}SS_TOKEN }}